app:
    name: h265-converter
    message: Hello ${app.name}}
    crf: 23
    preset: ultrafast

server:
    port: 9000

spring:
    data:
        elasticsearch:
            properties:
                http.enabled: true
                path.home: elasticsearch-data
                cluster.name: video-converter
                discovery.zen.ping.multicast.enabled: true
                network.host: ["_local_", "_site_"]
#                node.name: #{'$'}{HOSTNAME}

